### ISSUE TITLE
Add more maintainers

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#3275]
@awesomeWM/write-access All of you (including me) seem to be busy doing other things than AwesomeWM. The graph in https://github.com/awesomeWM/awesome/graphs/contributors looks pretty low for the last year.

So... should we switch from requiring two reviews on a PR to only one? (Although that wouldn't change anything currently since we also require a successful Travis build and non-negative coverage change.)

Should we give more people write access in this organisation?

Who would be candidates? More importantly, who also "self-nominates" in the sense of "I want to do this and I might have some time to do reviews"?

(Dear reader, we are using mergify.io, which means that a PR which meets [some requirements](https://github.com/awesomeWM/awesome/blob/master/.mergify.yml) is automatically merged. The requirements include two approving reviews.)

I'm obviously biased (I'm only human), but aire-one, kolo1337, and SirAidali seem to be names that I often see answer questions on https://www.reddit.com/r/awesomewm/. This is the best metric for "might know what they are doing and could review patches here" that I came up.

**Comment by jd** [comment]
Thanks for starting this @psychon!
I didn't follow anything for the last years so I don't have anything to say here.

As a first step, you could probably lower the barrier of review for core contributors with a rule such as:
```
  - name: automatic merge
    conditions:
      - label!=no-mergify
      - '#approved-reviews-by>=1'
      - author=@awesomeWM/write-access
      - status-success=Travis CI - Pull Request
      - status-success=codecov/patch
      - status-success=coverage/coveralls
    actions:
      merge:
        method: merge
```

My 2c!
